#pragma once
#include "StepData.h"
#include "TrackState.h"
#include <functional>
#include <vector>
#include <array>
#include <map>
#include <string>
#include <random>

// Event generated by the sequencer for the audio engine to process
struct SeqEvent
{
    enum Type { DrumTrigger, SynthNoteOn };

    Type     type = DrumTrigger;
    int      trackIndex = 0;      // drum: 0-9, synth: 0-4
    int      stepIndex = 0;       // which step triggered this
    int      sampleOffset = 0;    // sample position within the current buffer
    float    velocity = 0.0f;     // 0-1 normalised
    float    gateScale = 1.0f;    // combined gate + noteLen scaling
    NoteInfo note;                // for synth: note + octave
    int      ratchetIndex = 0;    // which ratchet hit (0 = first)
    bool     slide = false;       // 303-style slide flag
    bool     trigless = false;    // automation-only: p-locks without note trigger
    int      arpStepIndex = -1;  // arp step index from sequencer (-1 = not arp)
    int8_t   sampleSlot = -1;   // -1=track default, 0-127=per-step sample from folder

    // Chord notes
    std::vector<NoteInfo> chordNotes;

    // P-locks: OWNED COPY — plocks pointer always points to OUR plockData
    std::map<std::string, float> plockData;
    const std::map<std::string, float>* plocks = nullptr;

    // Copy constructor — fix up plocks pointer to point to OUR copy
    SeqEvent() = default;
    SeqEvent (const SeqEvent& o)
        : type(o.type), trackIndex(o.trackIndex), stepIndex(o.stepIndex),
          sampleOffset(o.sampleOffset), velocity(o.velocity), gateScale(o.gateScale),
          note(o.note), ratchetIndex(o.ratchetIndex), slide(o.slide), trigless(o.trigless),
          arpStepIndex(o.arpStepIndex), sampleSlot(o.sampleSlot),
          chordNotes(o.chordNotes), plockData(o.plockData)
    {
        plocks = plockData.empty() ? nullptr : &plockData;
    }

    SeqEvent& operator= (const SeqEvent& o)
    {
        if (this != &o)
        {
            type = o.type; trackIndex = o.trackIndex; stepIndex = o.stepIndex;
            sampleOffset = o.sampleOffset; velocity = o.velocity; gateScale = o.gateScale;
            note = o.note; ratchetIndex = o.ratchetIndex; slide = o.slide; trigless = o.trigless;
            arpStepIndex = o.arpStepIndex; sampleSlot = o.sampleSlot;
            chordNotes = o.chordNotes; plockData = o.plockData;
            plocks = plockData.empty() ? nullptr : &plockData;
        }
        return *this;
    }

    SeqEvent (SeqEvent&& o) noexcept
        : type(o.type), trackIndex(o.trackIndex), stepIndex(o.stepIndex),
          sampleOffset(o.sampleOffset), velocity(o.velocity), gateScale(o.gateScale),
          note(o.note), ratchetIndex(o.ratchetIndex), slide(o.slide), trigless(o.trigless),
          arpStepIndex(o.arpStepIndex), sampleSlot(o.sampleSlot),
          chordNotes(std::move(o.chordNotes)), plockData(std::move(o.plockData))
    {
        plocks = plockData.empty() ? nullptr : &plockData;
        o.plocks = nullptr;
    }

    SeqEvent& operator= (SeqEvent&& o) noexcept
    {
        if (this != &o)
        {
            type = o.type; trackIndex = o.trackIndex; stepIndex = o.stepIndex;
            sampleOffset = o.sampleOffset; velocity = o.velocity; gateScale = o.gateScale;
            note = o.note; ratchetIndex = o.ratchetIndex; slide = o.slide; trigless = o.trigless;
            arpStepIndex = o.arpStepIndex; sampleSlot = o.sampleSlot;
            chordNotes = std::move(o.chordNotes); plockData = std::move(o.plockData);
            plocks = plockData.empty() ? nullptr : &plockData;
            o.plocks = nullptr;
        }
        return *this;
    }

    void capturePlocks (const std::map<std::string, float>* src)
    {
        if (src != nullptr && !src->empty())
        {
            plockData = *src;
            plocks = &plockData;
        }
        else
        {
            plockData.clear();
            plocks = nullptr;
        }
    }
};

// Arp rate durations in beats (quarter notes)
static constexpr float kArpRateBeats[] = {
    0.125f,  // 0: 1/32
    0.1667f, // 1: 1/16T
    0.25f,   // 2: 1/16
    0.5f,    // 3: 1/8
    0.3333f, // 4: 1/8T
    1.0f,    // 5: 1/4
    2.0f,    // 6: 1/2
    4.0f     // 7: 1 bar
};

class SequencerEngine
{
public:
    SequencerEngine();

    // ── Extended chord types (24) with up to 6 intervals ──
    static constexpr int kNumChordTypes = 24;
    static constexpr int kMaxChordNotes = 6;
    static constexpr int chordTable[25][6] = {
        { -1,-1,-1,-1,-1,-1 }, // 0  OFF
        {  4, 7,-1,-1,-1,-1 }, // 1  MAJ
        {  3, 7,-1,-1,-1,-1 }, // 2  MIN
        {  4, 7,10,-1,-1,-1 }, // 3  7 (dom7)
        {  4, 7,11,-1,-1,-1 }, // 4  MAJ7
        {  3, 7,10,-1,-1,-1 }, // 5  MIN7
        {  3, 6,-1,-1,-1,-1 }, // 6  DIM
        {  4, 8,-1,-1,-1,-1 }, // 7  AUG
        {  2, 7,-1,-1,-1,-1 }, // 8  SUS2
        {  5, 7,-1,-1,-1,-1 }, // 9  SUS4
        {  4, 7,14,-1,-1,-1 }, // 10 ADD9
        {  7,-1,-1,-1,-1,-1 }, // 11 PWR
        { 12,-1,-1,-1,-1,-1 }, // 12 OCT
        {  3, 6, 9,-1,-1,-1 }, // 13 DIM7
        {  3, 6,10,-1,-1,-1 }, // 14 m7b5 (half-dim)
        {  4, 8,10,-1,-1,-1 }, // 15 AUG7
        {  3, 7,11,-1,-1,-1 }, // 16 mMAJ7
        {  4, 7, 9,-1,-1,-1 }, // 17 6
        {  3, 7, 9,-1,-1,-1 }, // 18 m6
        {  4, 7,10,14,-1,-1 }, // 19 9 (dom9)
        {  4, 7,11,14,-1,-1 }, // 20 MAJ9
        {  3, 7,10,14,-1,-1 }, // 21 MIN9
        {  5, 7,10,-1,-1,-1 }, // 22 7SUS4
        {  4, 7,17,-1,-1,-1 }, // 23 ADD11
        {  4, 7,10,14,21,-1 }, // 24 13
    };

    static const char* chordName (int type)
    {
        static const char* names[] = {
            "OFF","MAJ","MIN","7","M7","m7","DIM","AUG","SUS2","SUS4",
            "AD9","PWR","OCT","DM7","m7b5","AU7","mM7","6","m6",
            "9","M9","m9","7S4","AD11","13"
        };
        return (type >= 0 && type <= 24) ? names[type] : "?";
    }

    // Build chord notes from root + type + inversion + voicing
    static std::vector<NoteInfo> buildChord (NoteInfo root, int chordType, int inversion, int voicing,
                                              int scaleType = 0, int scaleRoot = 0);

    void prepare (double sampleRate);
    void reset();

    // Call from processBlock — fills events vector with triggers for this buffer
    void processBlock (int numSamples,
                       std::vector<SeqEvent>& events,
                       const std::array<DrumTrackState, 10>& drums,
                       const std::array<SynthTrackState, 5>& synths);

    // Transport
    void setPlaying (bool shouldPlay);
    bool isPlaying() const { return playing; }
    void stop();

    void setBPM (float newBPM);
    float getBPM() const { return bpm; }

    void setGlobalSwing (int swing) { globalSwing = swing; }
    int  getGlobalSwing() const { return globalSwing; }

    void setFillMode (bool on) { fillMode = on; }
    bool getFillMode() const { return fillMode; }

    void setScale (int root, int type) { scaleRoot = root; scaleType = type; }
    int getScaleRoot() const { return scaleRoot; }
    int getScaleType() const { return scaleType; }

    // For UI: get which step is currently playing per track
    int getDrumPlayingStep (int trackIdx) const;
    int getSynthPlayingStep (int trackIdx) const;
    int getMasterFXPlayingStep () const { return masterFXClock.currentStep; }
    int getDrumCurrentStep (int track) const { return (track >= 0 && track < 10) ? drumClocks[static_cast<size_t>(track)].currentStep : -1; }
    int getSynthCurrentStep (int track) const { return (track >= 0 && track < 5) ? synthClocks[static_cast<size_t>(track)].currentStep : -1; }
    void setMasterFXLength (int len) { masterFXLength = std::max (1, len); }

private:
    double sampleRate = 44100.0;
    float  bpm = 120.0f;
    int    globalSwing = 0;
    int    scaleRoot = 0;
    int    scaleType = 0;
    bool   playing = false;
    bool   fillMode = false;

    std::mt19937 rng { std::random_device{}() };

    // Per-track playback position (matches HTML dNext/dBeat pattern)
    struct TrackClock
    {
        double nextSamplePos = 0.0;   // absolute sample position of next step
        int    beatCounter   = 0;     // which beat we're on
        int    currentStep   = -1;    // last step triggered (for UI display)
        int    logicalStep   = 0;     // actual step in pattern (respects play direction)
        int    pingDir       = 1;     // +1 forward, -1 backward (for PING mode)
        bool   oneShotDone   = false; // for ONE mode: stops after last step
    };

    std::array<TrackClock, 10> drumClocks;
    std::array<TrackClock, 5> synthClocks;
    TrackClock masterFXClock;  // Master FX step sequencer clock
    int masterFXLength = 16;

    double globalSamplePos = 0.0;

    // Per-step cycle counters for n-of-m trig conditions
    // key = "trackType:trackIdx:stepIdx", value = loop count
    std::map<int, int> trigCycleCounters;

    // Pending ratchet events that fell outside the current buffer
    struct PendingEvent
    {
        SeqEvent event;
        double   absoluteSamplePos;   // when it should fire
    };
    std::vector<PendingEvent> pendingDrumEvents;
    std::vector<PendingEvent> pendingSynthEvents;

    // Arp runtime state per synth track
    struct ArpState
    {
        std::vector<NoteInfo> pool;
        int    idx        = 0;
        double nextTime   = 0.0;
        double openUntil  = 0.0;
        float  vel        = 0.8f;
        int    swingCount = 0;
        std::map<std::string, float> plockData;  // owned copy
        const std::map<std::string, float>* plocks = nullptr;
        void capturePlocks (const std::map<std::string, float>* src)
        {
            if (src && !src->empty()) { plockData = *src; plocks = &plockData; }
            else { plockData.clear(); plocks = nullptr; }
        }
    };
    std::array<ArpState, 5> arpStates;

    // ── Helpers ──
    double stepDurationSamples (float clockMul) const;
    bool shouldTrigger (const StepData& step, int trackKey, int stepIdx);
    int makeTrigKey (int trackType, int trackIdx, int stepIdx) const;

    // Compute current step index respecting play direction, then advance logicalStep
    int getAndAdvanceStep (TrackClock& clock, int playDir, int length)
    {
        int len = std::max (1, length);
        if (clock.oneShotDone) return -1;  // ONE mode finished

        int step = clock.logicalStep;

        // Advance to next step based on direction
        switch (playDir)
        {
            default:
            case 0: // FWD
                clock.logicalStep = (clock.logicalStep + 1) % len;
                break;
            case 1: // REV
                clock.logicalStep = (clock.logicalStep - 1 + len) % len;
                break;
            case 2: // PING (ping-pong)
                clock.logicalStep += clock.pingDir;
                if (clock.logicalStep >= len)
                {
                    clock.logicalStep = std::max (0, len - 2);
                    clock.pingDir = -1;
                }
                else if (clock.logicalStep < 0)
                {
                    clock.logicalStep = std::min (1, len - 1);
                    clock.pingDir = 1;
                }
                break;
            case 3: // RND
                clock.logicalStep = static_cast<int>(rng() % static_cast<unsigned>(len));
                break;
            case 4: // ONE (one-shot forward)
                if (clock.logicalStep >= len - 1)
                    clock.oneShotDone = true;
                else
                    clock.logicalStep = clock.logicalStep + 1;
                break;
        }

        return std::clamp (step, 0, len - 1);
    }

    // Initialize logicalStep for a given direction on first beat
    void initLogicalStep (TrackClock& clock, int playDir, int length)
    {
        int len = std::max (1, length);
        clock.pingDir = 1;
        clock.oneShotDone = false;
        switch (playDir)
        {
            default:
            case 0: clock.logicalStep = 0; break;         // FWD: start at 0
            case 1: clock.logicalStep = len - 1; break;   // REV: start at end
            case 2: clock.logicalStep = 0; break;         // PING: start at 0
            case 3: clock.logicalStep = static_cast<int>(rng() % static_cast<unsigned>(len)); break;
            case 4: clock.logicalStep = 0; break;         // ONE: start at 0
        }
    }

    void processDrumTrack (int trackIdx, const DrumTrackState& track,
                           int numSamples, std::vector<SeqEvent>& events);
    void processSynthTrack (int trackIdx, const SynthTrackState& track,
                            int numSamples, std::vector<SeqEvent>& events);
    void processArpeggiator (int trackIdx, const SynthTrackState& track,
                             int numSamples, std::vector<SeqEvent>& events);

    void emitPendingEvents (std::vector<PendingEvent>& pending,
                            int numSamples, std::vector<SeqEvent>& events);

    void buildArpPool (int trackIdx, const SynthTrackState& track);
    std::vector<NoteInfo> sortArpPool (const std::vector<NoteInfo>& pool, int mode, int octaves);
};
